Update cd.yaml

diff --git a/.github/workflows/cd.yaml b/.github/workflows/cd.yaml
--- a/.github/workflows/cd.yaml
+++ b/.github/workflows/cd.yaml
@@ -48,9 +48,19 @@ jobs:
       - name: SSH into EC2 and deploy docker-compose.yaml
         run: |
           chmod 600 ~/thgkey.pem
-          ssh -tt -i ~/thgkey.pem -o StrictHostKeyChecking=no ubuntu@$EC2_PUBLIC_IP << EOF
-            docker --version
-          EOF
+          for i in {1..5}; do
+            ssh -tt -i ~/thgkey.pem -o StrictHostKeyChecking=no ubuntu@$EC2_PUBLIC_IP << EOF
+              docker --version
+            EOF
+            if [ $? -eq 0 ]; then
+              echo "SSH connection successful!"
+              break
+            else
+              echo "SSH connection failed. Retrying in 30 seconds..."
+              sleep 30
+            fi
+          done
+        shell: bash
 
   # Separate Job: Destroy Resources
   cleanup:
